baseURL = "https://www.abandoned.website/"
languageCode = "en-us"
title = "Abandoned Website v.2"
disableKinds = ["taxonomy", "term"]
summaryLength = 30
[params]
  description = "What if long-forgotten websites actually appeared abandoned?"
  title = "Abandoned.Website | Long-Forgotten, But Always Loved"
