# Build the site please
[build]
  command = "hugo --gc --minify"
  publish = "public"

# Assign all the post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirect from the default Netlify site to my custom domain
[[redirects]]
  from = "https://abandoned-website.netlify.app/*"
  to = "https://www.abandoned.website/:splat"
  status = 301
  force = true

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
    Content-Security-Policy = "default-src 'self' https://d33wubrfki0l68.cloudfront.net https://fonts.gstatic.com https://fonts.googleapis.com/ https://images.dog.ceo 'unsafe-inline' data:"
